export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log(
    "process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID: ",
    process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID as string
  );
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
